// Auto-generated by add_indices.py
import RegionGroupPicker from "./RegionGroupPicker";
import RegionViewLabelSVG from "./RegionViewLabelSVG";
import RegionViewShapeSVG from "./RegionViewShapeSVG";

export { RegionGroupPicker, RegionViewLabelSVG, RegionViewShapeSVG };
