// Auto-generated by add_indices.py
import RegionViewLabelSVG from './RegionViewLabelSVG'
import RegionViewShapeSVG from './RegionViewShapeSVG'

export {
  RegionViewLabelSVG,
  RegionViewShapeSVG,
}
