// Auto-generated by javascript_version.py
export const DATETIME_STR = "2023-11-11 10:09:36";
export const VERSION_DATETIME = new Date(DATETIME_STR);

const VERSION = { DATETIME_STR, VERSION_DATETIME };
export default VERSION;
